//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mina.Tools.CMRR {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mina.Tools.CMRR.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   20 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BALLOON_STRING_MAX {
            get {
                return ResourceManager.GetString("BALLOON_STRING_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   CMRR - Clipboard Monitor and RegEx Replace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_DISP_NAME {
            get {
                return ResourceManager.GetString("MENU_DISP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terminate App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EXIT_APP {
            get {
                return ResourceManager.GetString("MENU_EXIT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mina_CMRR_Mutex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MUTEX_NAME {
            get {
                return ResourceManager.GetString("MUTEX_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   goNext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XML_ATTR_GONEXT {
            get {
                return ResourceManager.GetString("XML_ATTR_GONEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XML_ATTR_MATCH {
            get {
                return ResourceManager.GetString("XML_ATTR_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XML_ATTR_NAME {
            get {
                return ResourceManager.GetString("XML_ATTR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   notifySeconds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XML_ATTR_NOTIFYSECONDS {
            get {
                return ResourceManager.GetString("XML_ATTR_NOTIFYSECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   replaceTo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XML_ATTR_REPLACE_TO {
            get {
                return ResourceManager.GetString("XML_ATTR_REPLACE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   setting.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XML_SETTING_FILENAME {
            get {
                return ResourceManager.GetString("XML_SETTING_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CMRRSetting/setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_SETTING {
            get {
                return ResourceManager.GetString("XPATH_SETTING", resourceCulture);
            }
        }
    }
}
